[project]
name = "dhs-slm-workshop"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pylance>=10.0.0",
    "transformers>=4.45.0",
    "torch",
    "torchvision",
    "ipykernel",
    "accelerate",
    "bitsandbytes",
    "sentencepiece",
    "protobuf",
    "datasets",
    "peft",
    "trl",
    "psutil",
    "gputil",
    "tabulate",
    "sentence-transformers",
    "qwen-vl-utils",
    "soundfile",
    "matplotlib",
]
